#ifndef SSL_VEHICLE_TRACKING_VISUALIZATION__VISIBILITY_CONTROL_H_
#define SSL_VEHICLE_TRACKING_VISUALIZATION__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define SSL_VEHICLE_TRACKING_VISUALIZATION_EXPORT __attribute__((dllexport))
#define SSL_VEHICLE_TRACKING_VISUALIZATION_IMPORT __attribute__((dllimport))
#else
#define SSL_VEHICLE_TRACKING_VISUALIZATION_EXPORT __declspec(dllexport)
#define SSL_VEHICLE_TRACKING_VISUALIZATION_IMPORT __declspec(dllimport)
#endif
#ifdef SSL_VEHICLE_TRACKING_VISUALIZATION_BUILDING_LIBRARY
#define SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC SSL_VEHICLE_TRACKING_VISUALIZATION_EXPORT
#else
#define SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC SSL_VEHICLE_TRACKING_VISUALIZATION_IMPORT
#endif
#define SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC_TYPE SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC
#define SSL_VEHICLE_TRACKING_VISUALIZATION_LOCAL
#else
#define SSL_VEHICLE_TRACKING_VISUALIZATION_EXPORT __attribute__((visibility("default")))
#define SSL_VEHICLE_TRACKING_VISUALIZATION_IMPORT
#if __GNUC__ >= 4
#define SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC __attribute__((visibility("default")))
#define SSL_VEHICLE_TRACKING_VISUALIZATION_LOCAL __attribute__((visibility("hidden")))
#else
#define SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC
#define SSL_VEHICLE_TRACKING_VISUALIZATION_LOCAL
#endif
#define SSL_VEHICLE_TRACKING_VISUALIZATION_PUBLIC_TYPE
#endif

#endif  // SSL_VEHICLE_TRACKING_VISUALIZATION__VISIBILITY_CONTROL_H_
